// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkzaxhcztfdxjetbrqnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZremF4aGN6dGZkeGpldGJycW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTk5MjksImV4cCI6MjA3NDE5NTkyOX0.YtU8uFqhtzbkddI8BeYCVOxFPqdJPhLZiXfhzfn1yyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});